# Generated by Django 5.2.4 on 2025-07-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('smoker', models.BooleanField()),
                ('exercise_frequency', models.CharField(max_length=50)),
                ('diet_quality', models.CharField(max_length=50)),
                ('disease_risk', models.CharField(max_length=50)),
            ],
        ),
    ]
